name: Docs
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/docs.yml
      - deliveries/javadoc/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
        - uses: actions/checkout@v4
        - uses: actions/upload-pages-artifact@v3
          with:
            path: deliveries/javadoc
        - uses: actions/deploy-pages@v4
          id: deployment