name: Test
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Java 21 and Maven dependencies
        uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: '21'
          cache: maven
      - name: Compile project
        run: mvn -B compile --file codex/pom.xml

  junit:
    name: JUnit 5
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Java 21 and Maven dependencies
        uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: '21'
          cache: maven
      - name: Run JUnit 5 tests
        run: mvn -B test --file codex/pom.xml
      - name: Report test results
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
          token: ${{ secrets.REPORTER_TOKEN }}